# Generated by Django 4.0.1 on 2024-04-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_examslot_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='duties',
            field=models.ManyToManyField(related_name='teachers', to='teacher.ExamSlot'),
        ),
    ]
