# Generated by Django 4.0.1 on 2024-04-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_examslot_teacher_alter_teacher_duties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examslot',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='duties',
            field=models.ManyToManyField(related_name='teachers', to='teacher.ExamSlot'),
        ),
    ]
