# Generated by Django 4.0.1 on 2024-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_examslot_teacher_alter_teacher_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='examslot',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
    ]
