# Generated by Django 4.0.1 on 2024-05-11 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_examslot_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examslot',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='examslot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
